spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.156.60:3306/jdbc?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    schema:
      - classpath:department.sql